app/app/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'app.views.index'),
    # Examples:
    url(r'^about/$', 'app.views.about'),
    url(r'^category/(?P<category_name>[-\w\d]+)/$', 'app.views.category'),
    url(r'^profile/(?P<slug>[-\w\d]+)/$', 'app.views.profile'),
    url(r'^calendar/$', 'app.views.calendar'),
    url(r'^calendar/(?P<category_name>[-\w\d]+)/$', 'app.views.events_view'),
    # url(r'^app/', include('app.foo.urls')),
    url(r'^accounts/', include('institutions.urls')),
    url(r'^signin/$', 'institutions.views.signin'),
    url(r'^signup/$', 'institutions.views.signup'),
    url(r'^dashboard/$', 'app.views.dashboard'),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^user_validation/$', 'app.views.user_validation'),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # password recovery urls
    url(r'^recover/',include('password_reset.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += patterns('',
#                            url(r'^__debug__/', include(debug_toolbar.urls)),
#                            )

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/institutions/forms.py
# -*- encoding: utf-8 -*-
#core Django Imports
from django import forms
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField, AuthenticationForm
from django.forms.extras import widgets

#Third party apps
#Project apps import
from .models import UserProfile, Category, Event, MailingList, Organization

class CustomUserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'placeholder':'Contraseña'}))
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput(attrs={'placeholder':'Confirmar Contraseña'}))
    username = forms.CharField(required=False, max_length=30)
    full_name = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={"placeholder":'Nombre Completo'}))
    email = forms.CharField(max_length=30,
                            widget=forms.TextInput(attrs={"placeholder":'Email'}))

    class Meta:
        model = UserProfile
        fields = ('email', 'full_name')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # field does not have access to the initial value
        # This is done here, rather than on the field, because the
        return self.initial["password"]

    def clean_password2(self):
            # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        #change the html class of all the elements
        for field in self.fields:
        #of the form to get bootstrap 3 styling
            self.fields[field].widget.attrs.update({'class':'form-control'})

        self.fields.keyOrder = ['email', 'full_name', 'password1', 'password2']
    def save(self, commit=True):
                # Save the provided password in hashed format
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class DashboardUserCreationForm(forms.ModelForm):
    """
    This form is used to create a user from the dashboard.
    """
    class Meta:
        model = UserProfile
        fields = ('email', 'full_name')

    def __init__(self, *args, **kwargs):
        super(DashboardUserCreationForm, self).__init__(*args, **kwargs)
        #change the html class of all the elements of the form to get
        #bootstrap 3 styling
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})



class UserProfileChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = UserProfile
        fields = ('full_name', 'email')
        widgets = {'user_form': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        super(UserProfileChangeForm, self).__init__(*args, **kwargs)
        #change the html class of all the elements of
        #the form to get bootstrap 3 styling
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})


class  UserProfileLoginForm(AuthenticationForm):
    """A Form for user login."""
    form_fields = ["username", "password"]
    username = forms.CharField(max_length=254, label="Correo Electronico",
                               widget=forms.TextInput(attrs={"placeholder":'Usuario'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}))

    def __init__(self, *args, **kwargs):
        super(UserProfileLoginForm, self).__init__(*args, **kwargs)
        #change the html class of all the elements of the form to get bootstrap 3 styling
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})


class OrganizationForm(forms.ModelForm):
    """Form used when creating a new organization"""

    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all())
    description = forms.CharField(label="Descripción", required=False,
                                  widget=forms.Textarea(attrs={'rows':'2'}))
    url = forms.URLField(max_length=255,
                         help_text='Por favor introduzca la URL de la pagina',
                         widget=forms.TextInput(attrs={'placeholder': 'http://www.website.com'}))

    class Meta:
        """declaration of the inherited class"""
        model = Organization
        fields = ('name',
                  'description',
                  'phone',
                  'url',
                  'address',
                  'province',
                  'categories',
                 )

    def __init__(self, *args, **kwargs):
        super(OrganizationForm, self).__init__(*args, **kwargs)
        #change the html class of all the elements
        #of the form to get bootstrap 3 styling
        for field in self.fields:
            if field != 'categories':
                self.fields[field].widget.attrs.update({'class':'form-control'})
            else:
                self.fields[field].widget.attrs.update({'class':'organization-category'})


class OrganizationPictureForm(forms.ModelForm):
    picture = forms.ImageField()

    class Meta:
        model = Organization
        fields = (
                'logo',
                )


class EventForm(forms.ModelForm):
    """Form to handle event forms"""
    description = forms.CharField(label="Descripción", widget=forms.Textarea(attrs={'rows':'5'}))
    from_date = forms.CharField(widget=forms.TextInput(attrs={
            'class':'date',
            })
        )
    to_date = forms.CharField(widget=forms.TextInput(attrs={
            'class':'date',
            })
        )
    
    class Meta:
        """Model inheritance settings"""
        model = Event
        fields = ('name',
                  'categories',
                  'cost',
                  'description',
                  'from_date',
                  'to_date',
                  'url',
                 )


    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        #change the html class of all the elements of the form to get bootstrap 3 styling
        for field in self.fields:
            if field != 'categories':
                self.fields[field].widget.attrs.update({'class':'form-control'})
            else:
                self.fields[field].widget.attrs.update({'class':'event-category'})


class MailingListForm(forms.ModelForm):

    class Meta:
        Model = MailingList
        fields = (
                'full_name',
                'email',
                'province',
                )

app/templates/accounts/signup.html
{% extends "base.html" %}

{% load staticfiles %}
{% block extra_css %}
<link rel="stylesheet" href="{{ STATIC_URL }}/css/chosen.css">
{% endblock extra_css %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 user-register-form">
    <h2 class="text-center">Registro de la Instituci&oacute;n</h2>
      <form action="." method="POST" enctype="multipart/form-data">
        {{ user_form.errors }}
        {{ organization_form.errors }}
        {% csrf_token %}
        <div class="form-group">
          <h4>*Nombre de Contacto</h4>
          {{ user_form.full_name }}
        </div>
        <div class="form-group">
          <h4>*Email</h4>
          {{ user_form.email }}
        </div>
        <div class="form-group">
          <h4>*Contrase&ntilde;a</h4>
          {{ user_form.password1 }}
        </div>
        <div class="form-group">
          <h4>*Repetir Contrase&ntilde;a</h4>
          {{ user_form.password2 }}
        </div>
        <div class="form-group">
          <h4>*Categor&iacute;as</h4>
          {{ organization_form.categories }}
        </div>
        <div class="form-group">
          <h4>*Nombre Organizacion</h4>
          {{ organization_form.name }}
        </div>
        <div class="form-group">
          <h4>Descripción</h4>
          {{ organization_form.description }}
        </div>
        <div class="form-group">
          <h4>Teléfono</h4>
          {{ organization_form.phone }}
        </div>
        <div class="form-group">
          <h4>Página Web</h4>
          {{ organization_form.url }}
        </div>
        <div class="form-group">
          <h4>Dirección</h4>
          {{ organization_form.address }}
        </div>
        <div class="form-group">
          <h4>Provincia</h4>
          {{ organization_form.province }}
        </div>
        <div class="form-group">
         <button class="btn btn-success pull-right" type="submit">Registrarse</button>
        </div>
        <p>* Este campo es obligatorio</p>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block extra_js %}
	<script type="text/javascript" src="{{ STATIC_URL }}js/chosen.jquery.js"></script>
  <script>
  {# Here goes the code for using the categories as a selectpicker#}
  $(document).ready(function(){
    $('#id_categories').chosen({});
  });
  </script>
{% endblock extra_js %}